// <auto-generated />
using System;
using DEPI_REALESTATE_DB.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DEPI_REALESTATE_DB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251015142607_add Properties and interactions")]
    partial class addPropertiesandinteractions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DEPI_REALESTATE_DB.Model.Amenity", b =>
                {
                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HasElectricityLine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("HasGasLine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("HasWaterLine")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("PropertyId");

                    b.ToTable("Amenities", "pros");
                });

            modelBuilder.Entity("DEPI_REALESTATE_DB.Model.Comment", b =>
                {
                    b.Property<Guid>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DateComment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("isLiked")
                        .HasColumnType("bit");

                    b.HasKey("CommentId");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserID");

                    b.ToTable("Comments", "interactions");
                });

            modelBuilder.Entity("DEPI_REALESTATE_DB.Model.Property", b =>
                {
                    b.Property<Guid>("PropertyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DateListed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("GoogleMapsUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PropertyPurpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Square")
                        .HasColumnType("real");

                    b.HasKey("PropertyId");

                    b.HasIndex("AgentId");

                    b.ToTable("Properties", "pros");
                });

            modelBuilder.Entity("DEPI_REALESTATE_DB.Model.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("RoleType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Roles", "accounts");
                });

            modelBuilder.Entity("DEPI_REALESTATE_DB.Model.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("DateJoined")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserID");

                    b.HasIndex("RoleId");

                    b.ToTable("Users", "accounts");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("DEPI_REALESTATE_DB.Model.Wishlist", b =>
                {
                    b.Property<Guid>("ListingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("PropertyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ListingID");

                    b.HasIndex("PropertyID");

                    b.HasIndex("UserID", "PropertyID")
                        .IsUnique();

                    b.ToTable("Wishlists", "interactions");
                });

            modelBuilder.Entity("DEPI_REALESTATE_DB.Model.Agent", b =>
                {
                    b.HasBaseType("DEPI_REALESTATE_DB.Model.User");

                    b.Property<string>("AgencyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ExperienceYears")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<float>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<int>("TaxIdentificationNumber")
                        .HasColumnType("int");

                    b.ToTable("Agents", "accounts");
                });

            modelBuilder.Entity("DEPI_REALESTATE_DB.Model.Broker", b =>
                {
                    b.HasBaseType("DEPI_REALESTATE_DB.Model.User");

                    b.Property<int>("LicenseID")
                        .HasColumnType("int");

                    b.Property<int>("NationalID")
                        .HasColumnType("int");

                    b.ToTable("Brokers", "accounts");
                });

            modelBuilder.Entity("DEPI_REALESTATE_DB.Model.Amenity", b =>
                {
                    b.HasOne("DEPI_REALESTATE_DB.Model.Property", "Property")
                        .WithOne("Amenity")
                        .HasForeignKey("DEPI_REALESTATE_DB.Model.Amenity", "PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("DEPI_REALESTATE_DB.Model.Comment", b =>
                {
                    b.HasOne("DEPI_REALESTATE_DB.Model.Property", "Property")
                        .WithMany("Comments")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DEPI_REALESTATE_DB.Model.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DEPI_REALESTATE_DB.Model.Property", b =>
                {
                    b.HasOne("DEPI_REALESTATE_DB.Model.Agent", "Agent")
                        .WithMany("Properties")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("DEPI_REALESTATE_DB.Model.User", b =>
                {
                    b.HasOne("DEPI_REALESTATE_DB.Model.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DEPI_REALESTATE_DB.Model.Wishlist", b =>
                {
                    b.HasOne("DEPI_REALESTATE_DB.Model.Property", "Property")
                        .WithMany("Wishlists")
                        .HasForeignKey("PropertyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DEPI_REALESTATE_DB.Model.User", "User")
                        .WithMany("Wishlists")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DEPI_REALESTATE_DB.Model.Agent", b =>
                {
                    b.HasOne("DEPI_REALESTATE_DB.Model.User", null)
                        .WithOne()
                        .HasForeignKey("DEPI_REALESTATE_DB.Model.Agent", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DEPI_REALESTATE_DB.Model.Broker", b =>
                {
                    b.HasOne("DEPI_REALESTATE_DB.Model.User", null)
                        .WithOne()
                        .HasForeignKey("DEPI_REALESTATE_DB.Model.Broker", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DEPI_REALESTATE_DB.Model.Property", b =>
                {
                    b.Navigation("Amenity")
                        .IsRequired();

                    b.Navigation("Comments");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("DEPI_REALESTATE_DB.Model.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DEPI_REALESTATE_DB.Model.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("DEPI_REALESTATE_DB.Model.Agent", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
